isequal(foodChain('foodChain4.xlsx'),foodChain_soln('foodChain4.xlsx'))
isequal(foodChain('foodChain5.xlsx'),foodChain_soln('foodChain5.xlsx'))
isequal(foodChain('foodChain6.xlsx'),foodChain_soln('foodChain6.xlsx'))
isequal(foodChain('foodChain7.xlsx'),foodChain_soln('foodChain7.xlsx'))
isequal(foodChain('foodChain8.xlsx'),foodChain_soln('foodChain8.xlsx'))
isequal(foodChain('foodChain9.xlsx'),foodChain_soln('foodChain9.xlsx'))